*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZHCM_VFCT_SS_CNT................................*
FORM GET_DATA_ZHCM_VFCT_SS_CNT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHCM_TFCT_SS_CNT WHERE
(VIM_WHERETAB) .
    CLEAR ZHCM_VFCT_SS_CNT .
ZHCM_VFCT_SS_CNT-MANDT =
ZHCM_TFCT_SS_CNT-MANDT .
ZHCM_VFCT_SS_CNT-CTTYP =
ZHCM_TFCT_SS_CNT-CTTYP .
ZHCM_VFCT_SS_CNT-BUKRS =
ZHCM_TFCT_SS_CNT-BUKRS .
ZHCM_VFCT_SS_CNT-PARCIAL =
ZHCM_TFCT_SS_CNT-PARCIAL .
ZHCM_VFCT_SS_CNT-MODALIDADE =
ZHCM_TFCT_SS_CNT-MODALIDADE .
ZHCM_VFCT_SS_CNT-VAL_FCT =
ZHCM_TFCT_SS_CNT-VAL_FCT .
ZHCM_VFCT_SS_CNT-VAL_SS =
ZHCM_TFCT_SS_CNT-VAL_SS .
    SELECT SINGLE * FROM ZHCM_TFCT_MODA WHERE
MODALIDADE = ZHCM_TFCT_SS_CNT-MODALIDADE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MODAT WHERE
MODALIDADE = ZHCM_TFCT_MODA-MODALIDADE AND
SPRPAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_CNT-TEXT =
ZHCM_TFCT_MODAT-TEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZHCM_VFCT_SS_CNT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHCM_VFCT_SS_CNT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHCM_VFCT_SS_CNT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHCM_VFCT_SS_CNT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHCM_TFCT_SS_CNT WHERE
  CTTYP = ZHCM_VFCT_SS_CNT-CTTYP AND
  BUKRS = ZHCM_VFCT_SS_CNT-BUKRS AND
  PARCIAL = ZHCM_VFCT_SS_CNT-PARCIAL .
    IF SY-SUBRC = 0.
    DELETE ZHCM_TFCT_SS_CNT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHCM_TFCT_SS_CNT WHERE
  CTTYP = ZHCM_VFCT_SS_CNT-CTTYP AND
  BUKRS = ZHCM_VFCT_SS_CNT-BUKRS AND
  PARCIAL = ZHCM_VFCT_SS_CNT-PARCIAL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHCM_TFCT_SS_CNT.
    ENDIF.
ZHCM_TFCT_SS_CNT-MANDT =
ZHCM_VFCT_SS_CNT-MANDT .
ZHCM_TFCT_SS_CNT-CTTYP =
ZHCM_VFCT_SS_CNT-CTTYP .
ZHCM_TFCT_SS_CNT-BUKRS =
ZHCM_VFCT_SS_CNT-BUKRS .
ZHCM_TFCT_SS_CNT-PARCIAL =
ZHCM_VFCT_SS_CNT-PARCIAL .
ZHCM_TFCT_SS_CNT-MODALIDADE =
ZHCM_VFCT_SS_CNT-MODALIDADE .
ZHCM_TFCT_SS_CNT-VAL_FCT =
ZHCM_VFCT_SS_CNT-VAL_FCT .
ZHCM_TFCT_SS_CNT-VAL_SS =
ZHCM_VFCT_SS_CNT-VAL_SS .
    IF SY-SUBRC = 0.
    UPDATE ZHCM_TFCT_SS_CNT ##WARN_OK.
    ELSE.
    INSERT ZHCM_TFCT_SS_CNT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHCM_VFCT_SS_CNT-UPD_FLAG,
STATUS_ZHCM_VFCT_SS_CNT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHCM_VFCT_SS_CNT.
  SELECT SINGLE * FROM ZHCM_TFCT_SS_CNT WHERE
CTTYP = ZHCM_VFCT_SS_CNT-CTTYP AND
BUKRS = ZHCM_VFCT_SS_CNT-BUKRS AND
PARCIAL = ZHCM_VFCT_SS_CNT-PARCIAL .
ZHCM_VFCT_SS_CNT-MANDT =
ZHCM_TFCT_SS_CNT-MANDT .
ZHCM_VFCT_SS_CNT-CTTYP =
ZHCM_TFCT_SS_CNT-CTTYP .
ZHCM_VFCT_SS_CNT-BUKRS =
ZHCM_TFCT_SS_CNT-BUKRS .
ZHCM_VFCT_SS_CNT-PARCIAL =
ZHCM_TFCT_SS_CNT-PARCIAL .
ZHCM_VFCT_SS_CNT-MODALIDADE =
ZHCM_TFCT_SS_CNT-MODALIDADE .
ZHCM_VFCT_SS_CNT-VAL_FCT =
ZHCM_TFCT_SS_CNT-VAL_FCT .
ZHCM_VFCT_SS_CNT-VAL_SS =
ZHCM_TFCT_SS_CNT-VAL_SS .
    SELECT SINGLE * FROM ZHCM_TFCT_MODA WHERE
MODALIDADE = ZHCM_TFCT_SS_CNT-MODALIDADE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MODAT WHERE
MODALIDADE = ZHCM_TFCT_MODA-MODALIDADE AND
SPRPAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_CNT-TEXT =
ZHCM_TFCT_MODAT-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHCM_VFCT_SS_CNT-TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHCM_VFCT_SS_CNT-TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHCM_VFCT_SS_CNT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHCM_VFCT_SS_CNT-CTTYP TO
ZHCM_TFCT_SS_CNT-CTTYP .
MOVE ZHCM_VFCT_SS_CNT-BUKRS TO
ZHCM_TFCT_SS_CNT-BUKRS .
MOVE ZHCM_VFCT_SS_CNT-PARCIAL TO
ZHCM_TFCT_SS_CNT-PARCIAL .
MOVE ZHCM_VFCT_SS_CNT-MANDT TO
ZHCM_TFCT_SS_CNT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHCM_TFCT_SS_CNT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHCM_TFCT_SS_CNT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHCM_TFCT_SS_CNT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHCM_VFCT_SS_CNT USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHCM_TFCT_SS_CNT-MANDT =
ZHCM_VFCT_SS_CNT-MANDT .
ZHCM_TFCT_SS_CNT-CTTYP =
ZHCM_VFCT_SS_CNT-CTTYP .
ZHCM_TFCT_SS_CNT-BUKRS =
ZHCM_VFCT_SS_CNT-BUKRS .
ZHCM_TFCT_SS_CNT-PARCIAL =
ZHCM_VFCT_SS_CNT-PARCIAL .
ZHCM_TFCT_SS_CNT-MODALIDADE =
ZHCM_VFCT_SS_CNT-MODALIDADE .
ZHCM_TFCT_SS_CNT-VAL_FCT =
ZHCM_VFCT_SS_CNT-VAL_FCT .
ZHCM_TFCT_SS_CNT-VAL_SS =
ZHCM_VFCT_SS_CNT-VAL_SS .
    SELECT SINGLE * FROM ZHCM_TFCT_MODA WHERE
MODALIDADE = ZHCM_TFCT_SS_CNT-MODALIDADE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MODAT WHERE
MODALIDADE = ZHCM_TFCT_MODA-MODALIDADE AND
SPRPAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_CNT-TEXT =
ZHCM_TFCT_MODAT-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHCM_VFCT_SS_CNT-TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHCM_VFCT_SS_CNT-TEXT .
    ENDIF.
ENDFORM.
