PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHCM_VFCT_SS_MOT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHCM_VFCT_SS_MOT-MASSN .
    FIELD ZHCM_VFCT_SS_MOT-MASSG .
    FIELD ZHCM_VFCT_SS_MOT-BUKRS .
    FIELD ZHCM_VFCT_SS_MOT-MOTIVO_FCT .
    FIELD ZHCM_VFCT_SS_MOT-TEXT_FCT .
    FIELD ZHCM_VFCT_SS_MOT-MOTIVO_SS .
    FIELD ZHCM_VFCT_SS_MOT-TEXT_SS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZHCM_VFCT_SS_MOT ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHCM_VFCT_SS_MOT-MASSN .
    FIELD ZHCM_VFCT_SS_MOT-MASSG .
    FIELD ZHCM_VFCT_SS_MOT-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
