*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZHCM_VFCT_SS_MOA................................*
FORM GET_DATA_ZHCM_VFCT_SS_MOA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHCM_TFCT_SS_MOA WHERE
(VIM_WHERETAB) .
    CLEAR ZHCM_VFCT_SS_MOA .
ZHCM_VFCT_SS_MOA-MANDT =
ZHCM_TFCT_SS_MOA-MANDT .
ZHCM_VFCT_SS_MOA-MASSN =
ZHCM_TFCT_SS_MOA-MASSN .
ZHCM_VFCT_SS_MOA-MASSG =
ZHCM_TFCT_SS_MOA-MASSG .
ZHCM_VFCT_SS_MOA-BUKRS =
ZHCM_TFCT_SS_MOA-BUKRS .
ZHCM_VFCT_SS_MOA-ACAO =
ZHCM_TFCT_SS_MOA-ACAO .
ZHCM_VFCT_SS_MOA-MOTIVO_FCT =
ZHCM_TFCT_SS_MOA-MOTIVO_FCT .
ZHCM_VFCT_SS_MOA-MOTIVO_SS =
ZHCM_TFCT_SS_MOA-MOTIVO_SS .
    SELECT SINGLE * FROM ZHCM_TFCT_MOTIV WHERE
MOTIVO = ZHCM_TFCT_SS_MOA-MOTIVO_FCT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MOTIVT WHERE
MOTIVO = ZHCM_TFCT_MOTIV-MOTIVO AND
SPRPAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_MOA-TEXT_FCT =
ZHCM_TFCT_MOTIVT-TEXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZHCM_TFCT_MOTVS WHERE
MOTIVO = ZHCM_TFCT_SS_MOA-MOTIVO_SS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MOTVST WHERE
MOTIVO = ZHCM_TFCT_MOTVS-MOTIVO AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_MOA-TEXT_SS =
ZHCM_TFCT_MOTVST-TEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZHCM_VFCT_SS_MOA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHCM_VFCT_SS_MOA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHCM_VFCT_SS_MOA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHCM_VFCT_SS_MOA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHCM_TFCT_SS_MOA WHERE
  MASSN = ZHCM_VFCT_SS_MOA-MASSN AND
  MASSG = ZHCM_VFCT_SS_MOA-MASSG AND
  BUKRS = ZHCM_VFCT_SS_MOA-BUKRS AND
  ACAO = ZHCM_VFCT_SS_MOA-ACAO .
    IF SY-SUBRC = 0.
    DELETE ZHCM_TFCT_SS_MOA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHCM_TFCT_SS_MOA WHERE
  MASSN = ZHCM_VFCT_SS_MOA-MASSN AND
  MASSG = ZHCM_VFCT_SS_MOA-MASSG AND
  BUKRS = ZHCM_VFCT_SS_MOA-BUKRS AND
  ACAO = ZHCM_VFCT_SS_MOA-ACAO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHCM_TFCT_SS_MOA.
    ENDIF.
ZHCM_TFCT_SS_MOA-MANDT =
ZHCM_VFCT_SS_MOA-MANDT .
ZHCM_TFCT_SS_MOA-MASSN =
ZHCM_VFCT_SS_MOA-MASSN .
ZHCM_TFCT_SS_MOA-MASSG =
ZHCM_VFCT_SS_MOA-MASSG .
ZHCM_TFCT_SS_MOA-BUKRS =
ZHCM_VFCT_SS_MOA-BUKRS .
ZHCM_TFCT_SS_MOA-ACAO =
ZHCM_VFCT_SS_MOA-ACAO .
ZHCM_TFCT_SS_MOA-MOTIVO_FCT =
ZHCM_VFCT_SS_MOA-MOTIVO_FCT .
ZHCM_TFCT_SS_MOA-MOTIVO_SS =
ZHCM_VFCT_SS_MOA-MOTIVO_SS .
    IF SY-SUBRC = 0.
    UPDATE ZHCM_TFCT_SS_MOA ##WARN_OK.
    ELSE.
    INSERT ZHCM_TFCT_SS_MOA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHCM_VFCT_SS_MOA-UPD_FLAG,
STATUS_ZHCM_VFCT_SS_MOA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHCM_VFCT_SS_MOA.
  SELECT SINGLE * FROM ZHCM_TFCT_SS_MOA WHERE
MASSN = ZHCM_VFCT_SS_MOA-MASSN AND
MASSG = ZHCM_VFCT_SS_MOA-MASSG AND
BUKRS = ZHCM_VFCT_SS_MOA-BUKRS AND
ACAO = ZHCM_VFCT_SS_MOA-ACAO .
ZHCM_VFCT_SS_MOA-MANDT =
ZHCM_TFCT_SS_MOA-MANDT .
ZHCM_VFCT_SS_MOA-MASSN =
ZHCM_TFCT_SS_MOA-MASSN .
ZHCM_VFCT_SS_MOA-MASSG =
ZHCM_TFCT_SS_MOA-MASSG .
ZHCM_VFCT_SS_MOA-BUKRS =
ZHCM_TFCT_SS_MOA-BUKRS .
ZHCM_VFCT_SS_MOA-ACAO =
ZHCM_TFCT_SS_MOA-ACAO .
ZHCM_VFCT_SS_MOA-MOTIVO_FCT =
ZHCM_TFCT_SS_MOA-MOTIVO_FCT .
ZHCM_VFCT_SS_MOA-MOTIVO_SS =
ZHCM_TFCT_SS_MOA-MOTIVO_SS .
    SELECT SINGLE * FROM ZHCM_TFCT_MOTIV WHERE
MOTIVO = ZHCM_TFCT_SS_MOA-MOTIVO_FCT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MOTIVT WHERE
MOTIVO = ZHCM_TFCT_MOTIV-MOTIVO AND
SPRPAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_MOA-TEXT_FCT =
ZHCM_TFCT_MOTIVT-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHCM_VFCT_SS_MOA-TEXT_FCT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHCM_VFCT_SS_MOA-TEXT_FCT .
    ENDIF.
    SELECT SINGLE * FROM ZHCM_TFCT_MOTVS WHERE
MOTIVO = ZHCM_TFCT_SS_MOA-MOTIVO_SS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MOTVST WHERE
MOTIVO = ZHCM_TFCT_MOTVS-MOTIVO AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_MOA-TEXT_SS =
ZHCM_TFCT_MOTVST-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHCM_VFCT_SS_MOA-TEXT_SS .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHCM_VFCT_SS_MOA-TEXT_SS .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHCM_VFCT_SS_MOA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHCM_VFCT_SS_MOA-MASSN TO
ZHCM_TFCT_SS_MOA-MASSN .
MOVE ZHCM_VFCT_SS_MOA-MASSG TO
ZHCM_TFCT_SS_MOA-MASSG .
MOVE ZHCM_VFCT_SS_MOA-BUKRS TO
ZHCM_TFCT_SS_MOA-BUKRS .
MOVE ZHCM_VFCT_SS_MOA-ACAO TO
ZHCM_TFCT_SS_MOA-ACAO .
MOVE ZHCM_VFCT_SS_MOA-MANDT TO
ZHCM_TFCT_SS_MOA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHCM_TFCT_SS_MOA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHCM_TFCT_SS_MOA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHCM_TFCT_SS_MOA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHCM_VFCT_SS_MOA USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHCM_TFCT_SS_MOA-MANDT =
ZHCM_VFCT_SS_MOA-MANDT .
ZHCM_TFCT_SS_MOA-MASSN =
ZHCM_VFCT_SS_MOA-MASSN .
ZHCM_TFCT_SS_MOA-MASSG =
ZHCM_VFCT_SS_MOA-MASSG .
ZHCM_TFCT_SS_MOA-BUKRS =
ZHCM_VFCT_SS_MOA-BUKRS .
ZHCM_TFCT_SS_MOA-ACAO =
ZHCM_VFCT_SS_MOA-ACAO .
ZHCM_TFCT_SS_MOA-MOTIVO_FCT =
ZHCM_VFCT_SS_MOA-MOTIVO_FCT .
ZHCM_TFCT_SS_MOA-MOTIVO_SS =
ZHCM_VFCT_SS_MOA-MOTIVO_SS .
    SELECT SINGLE * FROM ZHCM_TFCT_MOTIV WHERE
MOTIVO = ZHCM_TFCT_SS_MOA-MOTIVO_FCT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MOTIVT WHERE
MOTIVO = ZHCM_TFCT_MOTIV-MOTIVO AND
SPRPAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_MOA-TEXT_FCT =
ZHCM_TFCT_MOTIVT-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHCM_VFCT_SS_MOA-TEXT_FCT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHCM_VFCT_SS_MOA-TEXT_FCT .
    ENDIF.
    SELECT SINGLE * FROM ZHCM_TFCT_MOTVS WHERE
MOTIVO = ZHCM_TFCT_SS_MOA-MOTIVO_SS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZHCM_TFCT_MOTVST WHERE
MOTIVO = ZHCM_TFCT_MOTVS-MOTIVO AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHCM_VFCT_SS_MOA-TEXT_SS =
ZHCM_TFCT_MOTVST-TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHCM_VFCT_SS_MOA-TEXT_SS .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHCM_VFCT_SS_MOA-TEXT_SS .
    ENDIF.
ENDFORM.
