*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZHCM_VFCT_FUNDM.................................*
FORM GET_DATA_ZHCM_VFCT_FUNDM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHCM_TFCT_FUNDM WHERE
(VIM_WHERETAB) .
    CLEAR ZHCM_VFCT_FUNDM .
ZHCM_VFCT_FUNDM-MANDT =
ZHCM_TFCT_FUNDM-MANDT .
ZHCM_VFCT_FUNDM-MOTIVO =
ZHCM_TFCT_FUNDM-MOTIVO .
ZHCM_VFCT_FUNDM-VALID_FROM =
ZHCM_TFCT_FUNDM-VALID_FROM .
ZHCM_VFCT_FUNDM-VALID_TO =
ZHCM_TFCT_FUNDM-VALID_TO .
    SELECT SINGLE * FROM ZHCM_TFCT_FUNDMT WHERE
MOTIVO = ZHCM_TFCT_FUNDM-MOTIVO AND
VALID_FROM = ZHCM_TFCT_FUNDM-VALID_FROM AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZHCM_VFCT_FUNDM-FUNDMT =
ZHCM_TFCT_FUNDMT-FUNDMT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZHCM_VFCT_FUNDM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHCM_VFCT_FUNDM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHCM_VFCT_FUNDM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHCM_VFCT_FUNDM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHCM_TFCT_FUNDM WHERE
  MOTIVO = ZHCM_VFCT_FUNDM-MOTIVO AND
  VALID_FROM = ZHCM_VFCT_FUNDM-VALID_FROM .
    IF SY-SUBRC = 0.
    DELETE ZHCM_TFCT_FUNDM .
    ENDIF.
    DELETE FROM ZHCM_TFCT_FUNDMT WHERE
    MOTIVO = ZHCM_TFCT_FUNDM-MOTIVO AND
    VALID_FROM = ZHCM_TFCT_FUNDM-VALID_FROM .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHCM_TFCT_FUNDM WHERE
  MOTIVO = ZHCM_VFCT_FUNDM-MOTIVO AND
  VALID_FROM = ZHCM_VFCT_FUNDM-VALID_FROM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHCM_TFCT_FUNDM.
    ENDIF.
ZHCM_TFCT_FUNDM-MANDT =
ZHCM_VFCT_FUNDM-MANDT .
ZHCM_TFCT_FUNDM-MOTIVO =
ZHCM_VFCT_FUNDM-MOTIVO .
ZHCM_TFCT_FUNDM-VALID_FROM =
ZHCM_VFCT_FUNDM-VALID_FROM .
ZHCM_TFCT_FUNDM-VALID_TO =
ZHCM_VFCT_FUNDM-VALID_TO .
    IF SY-SUBRC = 0.
    UPDATE ZHCM_TFCT_FUNDM ##WARN_OK.
    ELSE.
    INSERT ZHCM_TFCT_FUNDM .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZHCM_TFCT_FUNDMT WHERE
    MOTIVO = ZHCM_TFCT_FUNDM-MOTIVO AND
    VALID_FROM = ZHCM_TFCT_FUNDM-VALID_FROM AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZHCM_TFCT_FUNDMT.
ZHCM_TFCT_FUNDMT-MOTIVO =
ZHCM_TFCT_FUNDM-MOTIVO .
ZHCM_TFCT_FUNDMT-VALID_FROM =
ZHCM_TFCT_FUNDM-VALID_FROM .
ZHCM_TFCT_FUNDMT-SPRAS =
SY-LANGU .
      ENDIF.
ZHCM_TFCT_FUNDMT-FUNDMT =
ZHCM_VFCT_FUNDM-FUNDMT .
    IF SY-SUBRC = 0.
    UPDATE ZHCM_TFCT_FUNDMT ##WARN_OK.
    ELSE.
    INSERT ZHCM_TFCT_FUNDMT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHCM_VFCT_FUNDM-UPD_FLAG,
STATUS_ZHCM_VFCT_FUNDM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHCM_VFCT_FUNDM.
  SELECT SINGLE * FROM ZHCM_TFCT_FUNDM WHERE
MOTIVO = ZHCM_VFCT_FUNDM-MOTIVO AND
VALID_FROM = ZHCM_VFCT_FUNDM-VALID_FROM .
ZHCM_VFCT_FUNDM-MANDT =
ZHCM_TFCT_FUNDM-MANDT .
ZHCM_VFCT_FUNDM-MOTIVO =
ZHCM_TFCT_FUNDM-MOTIVO .
ZHCM_VFCT_FUNDM-VALID_FROM =
ZHCM_TFCT_FUNDM-VALID_FROM .
ZHCM_VFCT_FUNDM-VALID_TO =
ZHCM_TFCT_FUNDM-VALID_TO .
    SELECT SINGLE * FROM ZHCM_TFCT_FUNDMT WHERE
MOTIVO = ZHCM_TFCT_FUNDM-MOTIVO AND
VALID_FROM = ZHCM_TFCT_FUNDM-VALID_FROM AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZHCM_VFCT_FUNDM-FUNDMT =
ZHCM_TFCT_FUNDMT-FUNDMT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHCM_VFCT_FUNDM-FUNDMT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHCM_VFCT_FUNDM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHCM_VFCT_FUNDM-MOTIVO TO
ZHCM_TFCT_FUNDM-MOTIVO .
MOVE ZHCM_VFCT_FUNDM-VALID_FROM TO
ZHCM_TFCT_FUNDM-VALID_FROM .
MOVE ZHCM_VFCT_FUNDM-MANDT TO
ZHCM_TFCT_FUNDM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHCM_TFCT_FUNDM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHCM_TFCT_FUNDM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHCM_TFCT_FUNDM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZHCM_TFCT_FUNDM-MOTIVO TO
ZHCM_TFCT_FUNDMT-MOTIVO .
MOVE ZHCM_TFCT_FUNDM-VALID_FROM TO
ZHCM_TFCT_FUNDMT-VALID_FROM .
MOVE SY-LANGU TO
ZHCM_TFCT_FUNDMT-SPRAS .
MOVE ZHCM_VFCT_FUNDM-MANDT TO
ZHCM_TFCT_FUNDMT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHCM_TFCT_FUNDMT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHCM_TFCT_FUNDMT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHCM_TFCT_FUNDMT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
