PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHCM_VFCT_SS_MOA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHCM_VFCT_SS_MOA-MASSN .
    FIELD ZHCM_VFCT_SS_MOA-MASSG .
    FIELD ZHCM_VFCT_SS_MOA-BUKRS .
    FIELD ZHCM_VFCT_SS_MOA-ACAO .
    FIELD ZHCM_VFCT_SS_MOA-MOTIVO_FCT .
    FIELD ZHCM_VFCT_SS_MOA-TEXT_FCT .
    FIELD ZHCM_VFCT_SS_MOA-MOTIVO_SS .
    FIELD ZHCM_VFCT_SS_MOA-TEXT_SS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZHCM_VFCT_SS_MOA ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHCM_VFCT_SS_MOA-MASSN .
    FIELD ZHCM_VFCT_SS_MOA-MASSG .
    FIELD ZHCM_VFCT_SS_MOA-BUKRS .
    FIELD ZHCM_VFCT_SS_MOA-ACAO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
