PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHCM_TFCT_PRTLOG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHCM_TFCT_PRTLOG-SYSID .
    FIELD ZHCM_TFCT_PRTLOG-BUKRS .
    FIELD ZHCM_TFCT_PRTLOG-ADMI .
    FIELD ZHCM_TFCT_PRTLOG-CESS .
    FIELD ZHCM_TFCT_PRTLOG-MOD .
    FIELD ZHCM_TFCT_PRTLOG-SS_VINC .
    FIELD ZHCM_TFCT_PRTLOG-SS_MOD .
    FIELD ZHCM_TFCT_PRTLOG-SS_ALT_PER .
    FIELD ZHCM_TFCT_PRTLOG-SS_CESS .
    FIELD ZHCM_TFCT_PRTLOG-SS_CONSC .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHCM_TFCT_PRTLOG-SYSID .
    FIELD ZHCM_TFCT_PRTLOG-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
