*&---------------------------------------------------------------------*
*&  Include           ZHR_CARREGAMENTO_MEDIDAS_SSC
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME.

SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN COMMENT 1(30) ssc_file.

PARAMETERS:
            p_file TYPE localfile OBLIGATORY
          .
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN COMMENT 1(61) ssc_line.

PARAMETERS:
            p_lines TYPE i OBLIGATORY
          .

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME.

SELECTION-SCREEN BEGIN OF LINE.

* -------------------------------------------------
* INI ROFF SAM HR SS/EMP 7000030725 em 03.11.2016
* Comentado
*SELECTION-SCREEN
*PUSHBUTTON 5(32) badm USER-COMMAND uadm.
*
*SELECTION-SCREEN
*PUSHBUTTON 42(32) bdem USER-COMMAND udem.
*
*SELECTION-SCREEN
*PUSHBUTTON 77(32) bpro USER-COMMAND upro.

SELECTION-SCREEN
PUSHBUTTON 1(25) badm USER-COMMAND uadm.

SELECTION-SCREEN
PUSHBUTTON 27(25) bdem USER-COMMAND udem.

SELECTION-SCREEN
PUSHBUTTON 53(25) bpro USER-COMMAND upro.

SELECTION-SCREEN
PUSHBUTTON 79(25) baum USER-COMMAND uaum.
* END ROFF SAM HR SS/EMP 7000030725 em 03.11.2016
* -------------------------------------------------

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME.

* Mostra selecção pretendida ao utilizador
SELECTION-SCREEN COMMENT /2(70) ssc_com1 MODIF ID cb3.

* Informação do XLS escolhido
SELECTION-SCREEN COMMENT /5(60) ssc_com2.
SELECTION-SCREEN COMMENT /8(60) ssc_com3.
SELECTION-SCREEN COMMENT /8(60) ssc_com4.
SELECTION-SCREEN COMMENT /8(60) ssc_com5.
SELECTION-SCREEN COMMENT /8(60) ssc_com6.
SELECTION-SCREEN COMMENT /8(60) ssc_com7.

SELECTION-SCREEN END OF BLOCK b3.

SELECTION-SCREEN END OF BLOCK b2.
