class ZINETUMFCTCX_ALTERAR_CONTRATO definition
  public
  inheriting from CX_AI_APPLICATION_FAULT
  create public .

public section.

  data ALTERAR_CONTRATO_TRABALHO_EXCE type ZINETUMFCTALTERAR_CONTRATO_TR2 read-only .
  data AUTOMATIC_RETRY type PRX_AUTOMATIC_RETRY read-only .
  data CONTROLLER type PRXCTRLTAB read-only .
  data NO_RETRY type PRX_NO_RETRY read-only .
  data WF_TRIGGERED type PRX_WORKFLOW_TRIGGERED read-only .

  methods CONSTRUCTOR
    importing
      !TEXTID like TEXTID optional
      !PREVIOUS like PREVIOUS optional
      !ALTERAR_CONTRATO_TRABALHO_EXCE type ZINETUMFCTALTERAR_CONTRATO_TR2 optional
      !AUTOMATIC_RETRY type PRX_AUTOMATIC_RETRY optional
      !CONTROLLER type PRXCTRLTAB optional
      !NO_RETRY type PRX_NO_RETRY optional
      !WF_TRIGGERED type PRX_WORKFLOW_TRIGGERED optional .
protected section.
private section.
ENDCLASS.



CLASS ZINETUMFCTCX_ALTERAR_CONTRATO IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
TEXTID = TEXTID
PREVIOUS = PREVIOUS
.
me->ALTERAR_CONTRATO_TRABALHO_EXCE = ALTERAR_CONTRATO_TRABALHO_EXCE .
me->AUTOMATIC_RETRY = AUTOMATIC_RETRY .
me->CONTROLLER = CONTROLLER .
me->NO_RETRY = NO_RETRY .
me->WF_TRIGGERED = WF_TRIGGERED .
  endmethod.
ENDCLASS.
